### ISSUE TITLE
ALLOWED_HOSTS

### ISSUE THREAD

**Issue by brentgl** [swirlai/swirl-search#647]
Hi
looking forward to giving this a try
running on docker and get this error
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.1.79:8020'. You may need to add '192.168.1.79' to ALLOWED_HOSTS.

I have edited the .env file to add the IP after the localhost with and without comma, I have set it to 0.0.0.0, but any change doesn't produce anything - no error or page.
I did map 8020:8000 in ports, should I change the daphne -b 0.0.0.0 8000 to 8020 too? or leave as is?

Thanks

**Comment by MWP** [comment]
Same problem for me as well.

**Comment by erikspears** [comment]
Hi @brentgl ,

Sorry to hear you ran into this issue.  Have you tried running the latest Docker image as-is?  Swirl doesn't require ports be remapped as you indicated you were doing; everything is on 8000.  Would you mind trying to get a vanilla Docker run going and let us know if that works?  Also, the team is curious as to your use case for needing to remap ports?

Our Quick Start guide outlines the steps for getting the Docker fired up pretty quickly as well:  
https://github.com/swirlai/swirl-search/wiki/1.-Quick-Start#docker-installation

Thanks,
--Erik

**Comment by erikspears** [comment]
Hi @MWP , 

Please see the above comment in case it also pertains to your situation.  Could you provide a bit more detail about what you tried (e.g. following the guide for the Docker or something else) so that we can help troubleshoot?

Thanks,
--Erik

**Comment by ovizii** [comment]
> Hi @brentgl ,
> 
> Sorry to hear you ran into this issue. Have you tried running the latest Docker image as-is? Swirl doesn't require ports be remapped as you indicated you were doing; everything is on 8000. Would you mind trying to get a vanilla Docker run going and let us know if that works? Also, the team is curious as to your use case for needing to remap ports?
> 
> Our Quick Start guide outlines the steps for getting the Docker fired up pretty quickly as well: https://github.com/swirlai/swirl-search/wiki/1.-Quick-Start#docker-installation
> 
> Thanks, --Erik

I had the same issue so let me add my info: 

I am trying to run swirl on my nas and will be accessing it from my laptop which is within the same network so as I run multiple docker containers on my nas I need to map a specific port.

Also, would you please point me towards the correct instructions for "running the latest Docker image as-is"? 

What I tried was downloading this docker-compose and slightly adapting it: https://github.com/swirlai/swirl-search/blob/main/docker-compose.yaml

**Comment by erikspears** [comment]
Hi @ovizii ,

Thanks for the additional information, that helps a lot!  Let me chat a bit with the team about your setup before replying in detail.

As to the Docker installation instructions...they are here:  https://github.com/swirlai/swirl-search/wiki/1.-Quick-Start#docker-installation

More in a bit!
--Erik

**Comment by brentgl** [comment]
so I rolled out a vanilla VM with docker exactly according to your link
https://github.com/swirlai/swirl-search/wiki/1.-Quick-Start#docker-installation

I too access it from another PC on the network and get the django error still

Invalid HTTP_HOST header '192.168.1.213:8000' You may need to add '192.168.1.213' to ALLOWED_HOSTS.

Seems ALLOWED_HOSTS is set to localhost only in the .env files - I have tried to add as before the address but nothing.

And as for the why change port?  Well 8000 is one of the most common used ports out there and I was trying to run it on one of my existing VMs hence the port change.

Thanks
Brent

**Comment by ovizii** [comment]
I figured out the solution for this problem here: https://github.com/swirlai/swirl-search/issues/648#issuecomment-1739542798 please give it a try.

**Comment by brentgl** [comment]
> @brentgl Can you try adding 0.0.0.0 to your ALLOWED_HOSTS? That mask should allow all IPs. When I run Swirl on a separate host, I usually front-end it with a reverse-proxy such as ha-proxy.
> 
> Let us know if this works for you.
> 
> Jason

I tried to add the IP, 0.0.0.0 and * to either replace the initial locahost and also to append it on the end.  I guessed by looking at the settings.py that it wanted , (comma) separation between them but tried with spaces too.  No dice.

I have it 2 VMs now - a vanilla one and a prepoulated one - the snippet os from the one with the port changed

```
app_1    | 2023-09-28 11:32:58,703 INFO     Starting server at tcp:port=8000:interface=0.0.0.0
app_1    | 2023-09-28 11:32:58,705 INFO     HTTP/2 support not enabled (install the http2 and tls Twisted extras)
app_1    | 2023-09-28 11:32:58,706 INFO     Configuring endpoint tcp:port=8000:interface=0.0.0.0
app_1    | 2023-09-28 11:32:58,709 INFO     Listening on TCP address 0.0.0.0:8000
app_1    | 2023-09-28 11:33:02,114 ERROR    Invalid HTTP_HOST header: '192.168.1.79:8020'. You may need to add '192.168.1.79' to ALLOWED_HOSTS.
app_1    | Traceback (most recent call last):
app_1    |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
app_1    |     response = get_response(request)
app_1    |                ^^^^^^^^^^^^^^^^^^^^^
app_1    |   File "/usr/local/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
app_1    |     response = self.process_request(request)
app_1    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app_1    |   File "/usr/local/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
app_1    |     host = request.get_host()
app_1    |            ^^^^^^^^^^^^^^^^^^
app_1    |   File "/usr/local/lib/python3.11/site-packages/django/http/request.py", line 150, in get_host
app_1    |     raise DisallowedHost(msg)
app_1    | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.1.79:8020'. You may need to add '192.168.1.79' to ALLOWED_HOSTS.
app_1    | 2023-09-28 11:33:09,638 WARNING  Bad Request: /swirl
```

**Comment by TempleJason** [comment]
@brentgl are you editing settings.py directly or .env?  In the .env you said you have tried the following: 

ALLOWED_HOSTS=localhost,127.0.0.1,*

and that didn't work?  This is an internal django security setting.  If I'm running Swirl on another machine I usually front end it with ha-proxy (or some other reverse proxy).  Is that an option for you?

THanks,

Jason

**Comment by brentgl** [comment]
@TempleJason 
Didn't work in either place before.
But - I wiped the folder and re-done the docker instructions
added
```
    env_file:
      - .env
```
and created a .env with JUST

`ALLOWED_HOSTS=localhost,127.0.0.1,*
`
I am now officially "swirling" - works as should.

Thanks and Closing this!!
Brent

**Comment by erikspears** [comment]
That's great news, @brentgl !  Let us know if you have additional questions as you go!  We also have a free, [public Slack Community](https://join.slack.com/t/swirlmetasearch/shared_invite/zt-1qk7q02eo-kpqFAbiZJGOdqgYVvR1sfw) if that suits your needs in future. 

Take care,
--Erik

**Comment by jschwalbe** [comment]
This shouldn't be closed because it's going to continue to be an issue. I am here because I tried connecting to swirl over the network, and ran into the same error. You need to update the docker docs for folks not running on localhost docker.

**Comment by erikspears** [comment]
Hi @jschwalbe , sorry you ran into that issue, but I'm glad you found this Issue.  :)

I'll reopen this for now and ask our team about it next week.  Doc updates are important and these types of suggestions are good to hear, thank you!
--Erik

**Comment by erikspears** [comment]
Also, were you able to try any of the recommendations above, e.g. using a reverse proxy, in your situation @jschwalbe ?

**Comment by MWP** [comment]
> This shouldn't be closed because it's going to continue to be an issue. I am here because I tried connecting to swirl over the network, and ran into the same error. You need to update the docker docs for folks not running on localhost docker.

This is the problem im having also.
How did you fix it?

**Comment by ovizii** [comment]
> > This shouldn't be closed because it's going to continue to be an issue. I am here because I tried connecting to swirl over the network, and ran into the same error. You need to update the docker docs for folks not running on localhost docker.
> 
> This is the problem im having also. How did you fix it?

https://github.com/swirlai/swirl-search/issues/647#issuecomment-1739549642

**Comment by jschwalbe** [comment]
> How did you fix it?

create file called .env with contents: `ALLOWED_HOSTS='192.168.x.y'`
and reference from docker compose file: 
```
    env_file:
      - .env
```
