### ISSUE TITLE
Searches return: Error: Dictionary of result lengths is empty. 

### ISSUE THREAD

**Issue by ovizii** [swirlai/swirl-search#651]
I am running swirl for testing via docker. Any ideas?

Logs:

```
swirl_1      | 2023-09-28 11:35:08,681 INFO     admin search_qs 1
swirl_1      | 2023-09-28 11:35:18,808 WARNING  Timeout:The operation timed out. query results may still be returned
swirl_1      | 2023-09-28 11:35:18,808 INFO     search.py: FULL_RESULTS
swirl_1      | 2023-09-28 11:35:18,827 ERROR    CosineRelevancyPostResultProcessor_1: Error: Dictionary of result lengths is empty. Was CosineRelevancyResultProcessor included in Search Providers Processor configuration?
swirl_1      | 2023-09-28 11:35:18,832 INFO     admin search 1 FULL_RESULTS_READY 0 10.1
swirl_1      | 2023-09-28 11:35:18,850 INFO     admin results 1 RelevancyMixer 0
```

Actually, I jsut realized it might have been my fault, I was limiting the available memory to the swirl container to 4G with `mem_limit: 4G`

Any indications how much memory to allocate?
Could the error be configured to actually indicate the exact problem aka running out of memory?

**Comment by erikspears** [comment]
Hi @ovizii ,

Often the message about the CosineRelevancyPostResultProcessor indicates that this item is not present in the SearchProvider configuration.  That said, it should be present for all of our default (out of the box) SPs in the repo.  Are you creating a new SearchProvider?

The line about the Timeout simply means that at least one source is taking longer than 10s to return their response to Swirl.  As the message indicates, you may still see results from this source (Swirl tries to return results whenever possible).  Is this a new source you're search or one of the sources included out of the box?

And as to the memory allocation in Docker (I presume?), 4GB should be plenty.  We've had Swirl running fine in Docker containers with only 2GB allocated, although I wouldn't recomment that long-term.  :) 

Thanks,
--Erik

**Comment by ovizii** [comment]
Thanks for taking the time to have a look. Let me give you feedback:

- I am running your image out of the box with slight changes to the docker-compose.yml but nothing else
- as soon as I removed the memory limit and restarted the container all worked perfectly
- I followed your documentation screenshots and searched for "What is swirl metasearch?"
Btw. when limiting the swirl container to 4GB (trying to replicate the behavior I reported initially) I also seethis when starting:

```
swirl        | You're using version 2.6 of Swirl, the current version.
swirl        | Command successful!
swirl        | 2023-09-28 14:37:13,900 INFO     Starting server at tcp:port=8000:interface=0.0.0.0
swirl        | 2023-09-28 14:37:13,900 INFO     HTTP/2 support not enabled (install the http2 and tls Twisted extras)
swirl        | 2023-09-28 14:37:13,900 INFO     Configuring endpoint tcp:port=8000:interface=0.0.0.0
swirl        | 2023-09-28 14:37:13,901 INFO     Listening on TCP address 0.0.0.0:8000
swirl        | 2023-09-28 14:37:52,324 WARNING  Forbidden: /api/swirl/sapi/authenticators/
swirl        | 2023-09-28 14:37:52,325 WARNING  Forbidden: /api/swirl/sapi/searchproviders/
swirl        | 2023-09-28 14:37:52,487 WARNING  Forbidden: /api/swirl/sapi/searchproviders/
```

at this point, I cannot perform a search, the GUI seems to be simply hanging, hitting search does nothing and the logs do not show any reaction. 

Hitting log out results in these errors:

```
swirl        | 2023-09-28 14:40:38,382 ERROR    Internal Server Error: /api/swirl/logout/
swirl        | Traceback (most recent call last):
swirl        |   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
swirl        |     raise exc_info[1]
swirl        |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
swirl        |     response = await get_response(request)
swirl        |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
swirl        |   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
swirl        |     raise exc_info[1]
swirl        |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
swirl        |     response = await wrapped_callback(
swirl        |                ^^^^^^^^^^^^^^^^^^^^^^^
swirl        |   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
swirl        |     ret: _R = await loop.run_in_executor(
swirl        |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
swirl        |   File "/usr/local/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
swirl        |     result = self.fn(*self.args, **self.kwargs)
swirl        |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
swirl        |   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
swirl        |     return func(*args, **kwargs)
swirl        |            ^^^^^^^^^^^^^^^^^^^^^
swirl        |   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
swirl        |     return view_func(*args, **kwargs)
swirl        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
swirl        |   File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
swirl        |     return self.dispatch(request, *args, **kwargs)
swirl        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
swirl        |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
swirl        |     response = self.handle_exception(exc)
swirl        |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
swirl        |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
swirl        |     self.raise_uncaught_exception(exc)
swirl        |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
swirl        |     raise exc
swirl        |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
swirl        |     response = handler(request, *args, **kwargs)
swirl        |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
swirl        |   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
swirl        |     return view_func(*args, **kwargs)
swirl        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
swirl        |   File "/app/swirl/views.py", line 211, in post
swirl        |     token_obj = Token.objects.get(key=token)
swirl        |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
swirl        |   File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
swirl        |     return getattr(self.get_queryset(), name)(*args, **kwargs)
swirl        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
swirl        |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
swirl        |     raise self.model.DoesNotExist(
swirl        | rest_framework.authtoken.models.Token.DoesNotExist: Token matching query does not exist.
```

This looks like somehow I wasn't logged in any more, maybe I should have just tried refreshing the GUI in an anonymous browser window.

I logged in again and the search works, even with the 4GB limit, but it sticks very close to the 4GB:

```
docker stats | grep swirl
9e8c79ead014   swirl                   0.00%     3.847GiB / 4GiB       96.18%    601kB / 2.71MB    0B / 0B     39
615e509fcad7   swirl-redis             0.00%     5.113MiB / 512MiB     1.00%     385kB / 330kB     0B / 0B     6
```

I'm going to close the ticket as I wasn't looking for any solution, just wanted to report my findings in case it is of interest for you.

**Comment by erikspears** [comment]
Hi @ovizii ,

Thanks for all the feedback!

What you see above (first codeblock) when starting Docker is perfectly normal.  The "forbidden" lines are printed there because you have not yet logged into Django (the Swirl admin side of things).  Hence you are not yet allowed to see those endpoints.  Visit any of the them from [Swirl's Django homepage](https://github.com/swirlai/swirl-search/tree/main/docs) and enter the default username and password.  See this section of the Quick Start guide for more:  https://github.com/swirlai/swirl-search/wiki/1.-Quick-Start#open-the-swirl-homepage-django

The error you see when logging out of the Galaxy UI the first time is known and actually harmless.  We have an internal task to sort it out, but you may safely ignore it.  It will occur only when you are logging OUT of Galaxy while also not yet logged into Django.  :)

And finally...yes, it's likely that more than 4GB of memory allocated to your Docker will help things.  I tend to run mine with 8GB available to it, but I'm not eve really close to that.  I just like to have some padding in that regard.

Thanks again, this is great stuff, and please let us know if we can help.  You might also consider joining our [Community Slack](https://join.slack.com/t/swirlmetasearch/shared_invite/zt-1qk7q02eo-kpqFAbiZJGOdqgYVvR1sfw) as well!

Take care,
--Erik
